# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - iOS
        xcode:
          - ^15

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
    - name: Get swift version
      run: swift --version
    - uses: mxcl/xcodebuild@v1
      with:
        xcode: ${{ matrix.xcode }}
        platform: ${{ matrix.platform }}
